AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tomestones_api

  Sample SAM Template for tomestones_api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ConfigurationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: configuration/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        ConfigurationAll:
          Type: Api
          Properties:
            Path: /configuration
            Method: get
        Configuration:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RequestParameters:
              - method.request.path.jobid:
                Required: false
                Caching: false
            Path: /configuration/{jobid}
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TomestonesApi:
    Description: "API Gateway endpoint URL for Prod stage for Tomestones function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/configuration/"
  ConfigurationFunction:
    Description: "Configuration Lambda Function ARN"
    Value: !GetAtt ConfigurationFunction.Arn
  ConfigurationFunctionIamRole:
    Description: "Implicit IAM Role created for Tomestones function"
    Value: !GetAtt ConfigurationFunctionRole.Arn
